# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2026 Xueling Lin

import os

from pathlib import Path

_TESTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _TESTS_DIR.parent

# All test outputs live under an ignored tmp directory so test runs never
# pollute the repository, no matter which working directory pytest is
# launched from. Input fixture files are anchored to tests/data the same way.
TEST_OUTPUT_ROOT = str(_REPO_ROOT / "tmp" / "test_results")
TEST_DATA_ROOT = str(_TESTS_DIR / "data")

os.makedirs(TEST_OUTPUT_ROOT, exist_ok=True)


def _out(relative: str) -> str:
    return f"{TEST_OUTPUT_ROOT}/{relative}"


def _data(relative: str) -> str:
    return f"{TEST_DATA_ROOT}/{relative}"


SMALL_TEST_PATH = _out("small_dataset_test")
SAMPLE_FILES = {"jpg_1": _data("dogs.jpg"),
                "jpg_2": _data("cat-front.jpg"),
                "expected_json": _data("expected.json"),
                "expected_jsonl": _data("expected.jsonl"),
                "expected2_json": _data("expected2.json"),
                "expected2_jsonl": _data("expected2.jsonl")}
CIFAR10_TEST_PATH = _out("cifar10_test")
CIFAR10_MULTI_TEST_PATH = _out("cifar10_multi_test")

LARGE_TEST_PATH = _out("large_dataset_test")

TEST_APPEND_PATH = _out("test_append")
TEST_EXTEND_PATH = _out("test_extend")
TEST_APPEND_AND_EXTEND_PATH = _out("test_extend_and_append")
TEST_CLEAR_PATH = _out("test_clear")
TEST_CHECKPOINT_PATH = _out("test_checkpoint")

TEST_AGGREGATE_PATH = _out("test_aggregate")

TEST_RECHUNK_PATH = _out("test_rechunk")

VERSION_CONTROL_TEST_PATH = _out("version_control_dataset_test/")

VIEW_TEST_PATH = _out("view_test/")

DATASET_FILE = _data("text_data.txt")

TEST_INDEX_PATH = _out("index_dataset/")

TEST_DELETE_PATH = _out("delete_dataset/")

TEST_RENAME_PATH = _out("rename_dataset/")

TEST_LOAD_PATH = _out("load_dataset/")

TEST_NUMPY_PATH = _out("numpy_dataset/")

TEST_TENSOR_PATH = _out("tensor_dataset/")

TEST_JSON_PATH = _out("json_dataset")

TEST_JSONL_FILE = _out("test.jsonl")
TEST_JSON_FILE = _out("test.json")

HUASHAN_DATA_DIR = TEST_DATA_ROOT

LOCAL_DATA_DIR = "/data/muller_exp"

TEST_CACHE_PATH = _out("cache_dataset/")

TEST_FILTER_VECTORIZED_PATH = _out("filter_vectorized_dataset")

TEST_AGGREGATE_VECTORIZED_PATH = _out("aggregate_vectorized_dataset")

TEST_MULTI_USER_PATH = _out("multi_user_dataset")

TEST_MULTI_USER_MERGE_PATH = _out("multi_user_merge")

TEST_DETECT_MERGE = _out("detect_merge")

TEST_DETECT_ERROR = _out("detect_error")

TEST_TEMP_MERGE_PATH = _out("temp_merge_dataset")

TEST_MERGE_SCHEMA_PATH = _out("merge_schema_dataset")

TEST_MERGE_EDGE_PATH = _out("merge_edge_dataset")

TEST_COMPRESSION_PATH = _out("compression_dataset")

TEST_UUID_INDEX_PATH = _out("uuid_index_dataset")

TEST_PROCESS_INTERRUPT = _out("process_interrupt")

GIST_DATA_DIR = _out("gist_dataset/gist.npy")

TEST_CSV_DATASET_PATH = _out("csv_dataset_test")
# These CSVs are generated by the tests themselves (see _ensure_csv_* in
# test_from_csv.py) so they live under the output root, not tests/data.
CSV_WITH_PATHS_FILE = _out("csv_with_paths.csv")
CSV_TEXT_ONLY_FILE = _out("csv_text_only.csv")
CIFAR10_TRAIN_DIR = _data("cifar10/shared/train")
NUM_CIFAR10_SAMPLES = 10
